# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instabooks', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.FileField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
