# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instabooks', '0003_entry_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Album',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='album',
        ),
    ]
